### PR TITLE
[Enhacement] Updated Website - New UI (#17)

### LINKED ISSUE #17: [Enhancement]: Improving UI and Rectifying Errors
## Description
- Would like to contribute by improving the UI and styling of your Website
- Would like to work on header
- Filter and Sort Selective buttons 
- Glow Effect of Heart Icon

### PR DESCRIPTION
**Pull request by hariketsheth**
# Description
- Improved the UI and styling of your Website
- Worked on header
- Filter and Sort Selective buttons
- Glow Effect of Heart Icon
- Fixes #17 

# Screenshots
- Before
image

- After
image

### CODE REVIEW

**Comment by hariketsheth** [comment]
@ankitsaxena21 - I have created my PR, So I have added a Neumorphism styling to your website - removing the borders and making the website more engaging for users

**Comment by ankitsaxena21** [comment]
LGTM.

Thank you for contributing to this project @hariketsheth .

**Comment by hariketsheth** [comment]
@ankitsaxena21 Thanks for reviewing ! 
Can I request you to please add the *hactoberfest-accepted* label.

**Comment by ankitsaxena21** [comment]
Done

**Pull request merged**
